### ISSUE TITLE
Incorrect durations in report

### ISSUE THREAD

**Issue by BartKerkhoff** [philips-software/amp-cucumber-cpp-runner#102]
When generating a report (either a custom report or the `junit-xml` report), both the overal duration as the feature durations are not correct. Instead of reporting the sum of their children, they report the duration of their last executed child element. I.e. the overall duration matches the duration of the last feature and the feature durations match the duration of their last scenario.

This issue seems to be caused by the `ContextManager`. It only pushes new entries on the `activeContextStack`, entries never get popped. I would have expected that the `ScopedContextLock` popped the last element of this stack in its destructor. That way, when the scope of the lock ends, the higher level context gets restored. 

Unfortunately, the solution is not that simple... An exception seems to exist for the `step` scopes; they don't get pushed on the `activeContextStack` but they are still using the `ScopedContextLock`. Having the `ScopedContextLock` pop the `activeContextStack` in case of a `step` scope would cause an issue. As I don't understand the full idea behind the two stacks here, I am not comfortable with fixing this myself.

**Comment by BartKerkhoff** [comment]
This issue will be addressed by the refactor in #104. I've confirmed that it works over there, so closing this issue.

**Comment by daantimmer** [comment]
Fixed by #104
